"""Max_participants zu Datenmodell hinzufügen

Revision ID: 306befd21274
Revises: 31e6faeb6479
Create Date: 2025-02-12 19:53:58.927179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306befd21274'
down_revision = '31e6faeb6479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
