""" Participantsfeld in Event Datenmodell hinzufügen

Revision ID: 31e6faeb6479
Revises: 4339f89e6ee9
Create Date: 2025-02-12 19:30:47.668113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e6faeb6479'
down_revision = '4339f89e6ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('participants')

    # ### end Alembic commands ###
