"""Initial migration

Revision ID: 4339f89e6ee9
Revises: b368d46a3de2
Create Date: 2025-02-12 19:11:47.907312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4339f89e6ee9'
down_revision = 'b368d46a3de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('event_creator_id_fkey', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('event_creator_id_fkey', 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###
