"""Weitere Änderungen am Event-Modell

Revision ID: a9ecc37fcd86
Revises: 863e4b18d4d9
Create Date: 2025-02-12 21:14:47.598106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ecc37fcd86'
down_revision = '863e4b18d4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=False))
        batch_op.alter_column('event_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('event_starttime',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('event_endtime',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('event_location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('max_participants',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['host_id'], ['id'])
        batch_op.drop_column('participants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('max_participants',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('event_endtime',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('event_starttime',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('event_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###
