"""Initial migration

Revision ID: b368d46a3de2
Revises: 
Create Date: 2025-02-12 19:10:46.535861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b368d46a3de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_participants')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.alter_column('event_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('event_date',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('event_starttime',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('event_endtime',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('event_location',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('event_event_creator_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])
        batch_op.drop_column('event_participants')
        batch_op.drop_column('event_creator')
        batch_op.drop_column('event_max_participants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_max_participants', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_creator', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_participants', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_event_creator_fkey', 'user', ['event_creator'], ['id'])
        batch_op.alter_column('event_location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('event_endtime',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('event_starttime',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('event_date',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('event_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('creator_id')

    op.create_table('event_participants',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_participants_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='event_participants_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name='event_participants_pkey')
    )
    # ### end Alembic commands ###
